Repository likeLion-FrontEnd-project/Hologram, pull requests merged in 2022-07, with the labels that each got.

#17 [Add] product 페이지 마크업, css
  assets/icon-arrow-left.png
  assets/img-gray-btn.png
  css/product.css
  pages/product.html
Labels: Add

#21 [Add] index.html, splash.css, splash.js와 이미지 파일 추가
  assets/images/icon-check.svg
  assets/images/icon-check_red.svg
  assets/images/icon-facebook.svg
  assets/images/icon-google.svg
  assets/images/icon-kakao.svg
  assets/images/logo.png
  css/default.css
  css/splash.css
  css/style.css
  index.html
  js/splash.js
Labels: Add

#27 [Add] tab-menu.html & tab-menu.css 파일 추가
  assets/tab-menu-sprites-color.png
  assets/tab-menu-sprites.png
  css/tab-menu.css
  html/tab-menu.html
Labels: Add

#28 [Add] login.html & login.css 파일 추가
  css/login.css
  pages/login.html
Labels: Add

#30 [Add] join.html & join.css 파일 추가
  css/join.css
  pages/join.html
Labels: Add

#18 [Add] chat.html & chat.css 파일 추가
  assets/live-img.png
  assets/menu-img.png
  assets/profile-img.png
  css/chat.css
  pages/chat.html
Labels: Add

#23 [Add] chatroom.html & chatroom.css 파일 추가
  assets/button-img.png
  assets/send-img.png
  css/chatroom.css
  pages/chatRoom.html
Labels: Add

#35 [Add] postcomment.html & postcomment.css 파일 추가
  assets/menu-gray-img.png
  assets/test-img.png
  css/postcomment.css
  pages/postcomment.html
Labels: Add

#43 [Update] chat.html & chat.css 아이콘 수정
  css/chat.css
  pages/chat.html
Labels: Update

#37 [Add] setprofile.html & setprofile.css 파일 및 이미지 파일 추가
  assets/images/icon-image.svg
  assets/images/img-profile.png
  css/setprofile.css
  pages/setprofile.html
Labels: Add

#49 [Update] 하단 tab-menu css 수정
  css/tab-menu.css
Labels: Update

#52 [Update] chatroom.html & chatroom.css 아이콘 수정 및 채팅 페이지 연결
  css/chatroom.css
  pages/chatroom.html
Labels: Update

#54 [Add] editprofile.html & editprofile.css 파일, 이미지 파일 추가
  assets/images/icon-arrow-left.svg
  css/editprofile.css
  pages/editprofile.html
Labels: Add

#59 [Rename] tab-menu 경로와 이미지명 변경
  css/tab-menu.css
Labels: Rename

#61 [Rename] profile 페이지 누락된 icon 추가
  assets/images/icon/icon-chat.svg
  assets/images/icon/icon-img-layers.svg
  assets/images/icon/icon-post-album-off.svg
  assets/images/icon/icon-post-album-on.svg
  assets/images/icon/icon-post-list-off.svg
  assets/images/icon/icon-post-list-on.svg
  assets/images/icon/icon-share.svg
Labels: Rename

#64 [Rename] product 페이지 html 경로, css 수정
  css/product.css
  pages/product.html
Labels: Rename

#66 [Add] 홈 피드 초기화면 html, css 추가
  assets/images/image-symbol-logo.png
  css/home.css
  css/tab-menu.css
  html/home.html
  html/tab-menu.html
Labels: Add

#71 [Add] 검색창 초기 화면
  css/search-init.css
  pages/search-init.html
Labels: Add

#74 [Add] 모달창 html, css 추가
  css/modal.css
  pages/modal-chat.html
  pages/modal-comment-delete.html
  pages/modal-comment-report.html
  pages/modal-post.html
  pages/modal-product.html
  pages/modal-profile.html
Labels: Add

#80 [Update] profile 페이지 html,css 수정 및 중복코드 제거
  css/profile.css
  pages/profile.html
Labels: Update

#77 [Add] followers 페이지 html, css
  css/followers.css
  pages/followers.html
Labels: Add

#84 [Update] chat.html footer 추가
  pages/chat.html
Labels: Update

#82 [Update] post.html 모달창 수정
  css/post.css
  pages/post.html
Labels: Update

#73 [Add] 검색창 결과 화면 html, css 추가
  css/search-result.css
  pages/search-result.html
Labels: Add

#76 [Add] 홈 피드 게시글 화면
  css/feed.css
  pages/feed.html
Labels: Add

#87 [Update] postcomment.css 프로필 이미지 형태 고정
  css/postcomment.css
Labels: Update

#98 [Update] 피드 프로필 폰트사이즈 변경 & 누락 아이콘 업로드
  assets/images/icon/icon-ThumbsDown-gray.svg
  assets/images/icon/icon-ThumbsDown-white.svg
  assets/images/icon/icon-ThumbsUp-gray.svg
  assets/images/icon/icon-ThumbsUp-white.svg
  assets/images/icon/icon-comments.svg
  assets/images/icon/icon-like-gray.svg
  assets/images/icon/icon-like-purple.svg
  assets/images/icon/icon-modal-closebtn.svg
  assets/images/icon/icon-search.svg
  css/feed.css
Labels: Update

#100 [Update] 모달창 css 변경
  css/modal.css
Labels: Update

#103 [Update] tab-menu html & css 수정
  css/tab-menu.css
  pages/feed.html
  pages/home.html
  pages/search-init.html
  pages/search-result.html
  pages/tab-menu.html
Labels: Update

#105 [Update] post.html 이미지 링크 변경 & post.css 이미지 업로드 스타일 변경
  css/post.css
  pages/post.html
Labels: Update

#107 [Update] profile.html,css 피드 추가 및 코드 수정
  css/profile.css
  js/profile.js
  pages/profile.html
Labels: Update

#94 [Update] join, setprofile 파트 통합 & setprofile.html, setprofile.css 파일 삭제
  css/join.css
  css/setprofile.css
  pages/join.html
  pages/setprofile.html
Labels: Update

#114 [Update] header html, css 통일/ common.css 추가
  css/common.css
  css/nav.css
  html/nav.html
Labels: Add, Update

#111 [Add] 게시글 작성 페이지 기능 구현
  js/post.js
Labels: Add

#129 [Update] 누락된 공통 header UI(chat-nav) 추가
  css/nav.css
  html/nav.html
Labels: Update

#120 [Add] login.html, login.css 수정 & login.js 파일 추가
  css/login.css
  js/login.js
  pages/login.html
Labels: Add, Update

#122 [Update] editprofile.html & editprofile.css 파일 수정
  css/editprofile.css
  pages/editprofile.html
Labels: Update

#119 [Update] profile.html, css 헤더, 피드, 탭메뉴 수정
  css/profile.css
  pages/profile.html
Labels: Update

#125 [Update] home,search html & css 코드 수정
  css/search-result.css
  pages/home.html
  pages/search-init.html
  pages/search-result.html
Labels: Update

#138 [Update] login.js 로컬스토리지 "accountname"값 추가 등록
  js/login.js
Labels: Update

#132 [Update] post.html & post.css 변경
  css/post.css
  js/post.js
  pages/post.html
Labels: Update

#127 [Add] 공통UI userList.html, css 구현
  css/userList.css
  html/userList.html
Labels: Add

#130 [Update] postcomment.html & postcomment.css
  css/postcomment.css
  pages/postcomment.html
Labels: Update

#134 [Update] chat.html & chat.css 변경
  css/chat.css
  pages/chat.html
Labels: Update

#136 [Update] home.html 파일 수정
  html/tab-menu.html
  pages/home.html
Labels: Update

#147 [Add] 공통 UI imageRegister.html & imageRegister.css 구현
  css/imageRegister.css
  html/imageRegister.html
Labels: Update

#143 [Update] nav.css에서 .title-nav 수정
  css/nav.css
Labels: Update

#150 [Update] 공통UI userList.css 수정
  css/userList.css
  html/userList.html
Labels: Update

#145 [Update] chatroom.html & chatroom.css 변경
  css/chatroom.css
  pages/chatroom.html
Labels: Update

#159 [Add] postcomment.js 파일 추가
  css/postcomment.css
  js/postcomment.js
  pages/postcomment.html
Labels: Add

#155 [Update] profile, product, followers, followings 페이지 html, css 수정
  assets/images/icon/.DS_Store
  css/followers.css
  css/followings.css
  css/product.css
  css/profile.css
  pages/followers.html
  pages/followings.html
  pages/product.html
  pages/profile.html
Labels: Update

#154 [Add] profile.js 로그인한 사용자 데이터 받아오기
  js/profile.js
Labels: Add

#157 [Add] 공통 UI input.html & input.css 파일 추가
  css/input.css
  html/input.html
Labels: Add

#152 [Update] post.css 모달창 수정
  css/post.css
Labels: Update

#161 [Update] 페이지별 링크 연결, 공통 js 연결
  css/chat.css
  css/chatroom.css
  css/default.css
  css/feed.css
  css/followings.css
  css/nav.css
  css/post.css
  css/postcomment.css
  css/profile.css
  css/search-init.css
  js/common.js
  js/post.js
  js/postcomment.js
  js/profile.js
  pages/chat.html
  pages/chatroom.html
  pages/editprofile.html
  pages/feed.html
  pages/followers.html
  pages/followings.html
  pages/home.html
  pages/modal-chat.html
  pages/modal-comment-delete.html
  pages/modal-comment-report.html
  pages/modal-post.html
  pages/modal-product.html
  pages/modal-profile.html
  pages/post.html
  pages/postcomment.html
  pages/product.html
  pages/profile.html
  pages/search-init.html
  pages/search-result.html
Labels: Update

#163 [Update] 피드 html&css 변경
  .vscode/settings.json
  css/feed.css
  html/feed.html
  pages/profile.html
Labels: Update

#167 [Update] post.html & post.css 수정
  css/post.css
  js/post.js
  pages/post.html
Labels: Update

#171 [Update] input.html & input.css 마크업 스타일 수정
  css/input.css
  html/input.html
Labels: Update

#175 [Update] 공통 UI 생성에 따라 login 파트 전체적으로 수정(html, css, js)
  css/login.css
  js/login.js
  pages/login.html
Labels: Update

#173 [Add] postcomment.js 댓글 불러오기 기능 추가
  js/postcomment.js
Labels: Add

#180 [Add] profile 페이지 html,css,js 상태별 프로필 정보
  css/profile.css
  js/profile.js
  pages/profile.html
Labels: Add

#178 [Add] feed.js, modal.js 업로드 & html, css 파일 수정
  css/feed.css
  css/modal.css
  html/feed.html
  js/feed.js
  js/feedmodal.js
  pages/home.html
Labels: Add, Update

#184 [Add] join 회원가입 기능 추가
  css/join.css
  js/join.js
  pages/join.html
Labels: Add

#182 [Add] postcomment.js 기능 추가
  css/postcomment.css
  js/postcomment.js
  pages/postcomment.html
Labels: Update

#187 [Add] home & feedDetail 추가 및 css 수정
  css/feed.css
  js/feedDetail.js
  js/home.js
  pages/feedDetail.html
  pages/home.html
Labels: Add, Update

#191 [Add] 검색창 js 파일 추가
  js/search.js
  pages/search-result.html
Labels: Add, Update

#192 [Add] following 목록 생성, userList 수정
  css/followings.css
  css/userList.css
  html/userList.html
  js/followings.js
  pages/followings.html
Labels: Add, Update

#194 [Add] profile 페이지 nav 모달 추가
  css/profile.css
  js/profile.js
  pages/profile.html
Labels: Add

#202 [Add] postcomment.js 기능 추가
  css/postcomment.css
  js/postcomment.js
  pages/postcomment.html
Labels: Update

#203 [Update] 홈, 검색창 ui & js 수정
  css/feed.css
  css/modal.css
  css/search-result.css
  js/feed.js
  js/feedDetail.js
  js/home.js
  js/search.js
  pages/home.html
  pages/search-result.html
Labels: Update

#210 [Add] 프로필 페이지 팔로우 버튼 기능
  css/profile.css
  js/profile.js
  pages/profile.html
Labels: Add, Update

#209 [Add] editprofile 기능 추가(기존 정보 입력값 유지 / 이미지 업로드 / 수정 데이터 갱신)
  css/editprofile.css
  js/editprofile.js
Labels: Add

#222 [Update] profile.js 수정
  js/profile.js
  pages/profile.html
Labels: Update

#219 [Add] product 페이지 이미지 등록, 상품명, 상품가격 유효성 검사
  css/product.css
  js/product.js
  pages/product.html
Labels: Add

#215 [Fix] 프로필 수정 후 내 정보 페이지에 데이터를 읽지 못하는 이슈 해결 및 스타일 수정
  css/editprofile.css
  js/editprofile.js
Labels: Update, Fix

#217 [Add] home.js 좋아요 기능 추가
  js/home.js
  js/search.js
  pages/home.html
Labels: Add

#226 [Add] profile-post.js 파일 업로드
  js/home.js
  js/profile-post.js
  pages/profile.html
Labels: Add

#224 [Add] product.js 기능 추가(입력값과 에러 상태에 따른 버튼 상태 / 상품 등록) 및 공통 UI nav.css 수정
  css/nav.css
  js/product.js
  pages/product.html
Labels: Add, Update

#231 [Add] 로그아웃 기능 & 채팅방 나가기 기능추가
  css/chatroom.css
  css/modal.css
  css/postcomment.css
  js/backchat.js
  js/common.js
  js/post.js
  js/postcomment.js
  pages/chat.html
  pages/chatroom.html
  pages/postcomment.html
Labels: Add

#230 [Add] 404 페이지 기능 구현(이전 페이지로 이동 버튼)
  pages/404.html
Labels: Add

#234 [Add] profile 페이지 판매 상품 탭 데이터 처리, 모달
  css/profile.css
  js/profile-product.js
  js/profile.js
  pages/profile.html
Labels: Add

#241 [Update] 홈 피드, 프로필페이지, 댓글페이지 좋아요 기능 수정
  css/feed.css
  html/feed.html
  js/home.js
  js/like.js
  js/postcomment.js
  js/profile-post.js
Labels: Update

#238 [Fix] 프로필 수정 페이지 버그 수정(새로운 계정ID 입력 후 기존 계정ID를 다시 입력 시 에러 메세지 발생)
  js/editprofile.js
Labels: Fix

#250 [Add] 게시글 수정 ,삭제, 신고 기능 추가 & 댓글 프로필 클릭 시 프로필 페이지 이동
  css/modal.css
  js/editpost.js
  js/postcomment.js
  js/profile-post.js
  pages/editpost.html
  pages/profile.html
Labels: Add, Update

#247 [Fix] 팔로워, 팔로잉 페이지 팔로워만 보이는 현상 해결
  js/follow.js
Labels: Fix

#251 [Add] 프로필 페이지 앨범뷰 전환 기능 추가
  js/postcomment.js
  js/profile-post.js
  js/profile.js
  pages/profile.html
Labels: Add

#253 [Add] profile 페이지 게시글 영역 조건부 렌더링
  js/profile.js
Labels: Add

#260 [Fix] profile 페이지 아이디,자기소개 글자 수 넘침, 팔로우버튼 깨짐
  css/feed.css
  css/profile.css
  js/profile.js
Labels: Fix, Design

#263 [Update] 게시물 수정 클릭 시 원래 게시물 받아오기 / 댓글 작성 부분 프로필 이미지 변경 & 댓글 작성 에러 처리 / 채팅방 채팅 시 버튼 on / 게시글 선택하기 제외시키기 기능 추가
  css/chatroom.css
  css/post.css
  css/postcomment.css
  js/chatroom.js
  js/editpost.js
  js/post.js
  js/postcomment.js
  pages/chatroom.html
Labels: Update, Fix

#256 [Add] splash 페이지 로드 후 localstorage에 token이 존재 시 feed 페이지로 이동하는 기능 구현
  js/splash.js
Labels: Add

#257 [Update] 회원가입 수정사항 적용(유효성 검사 컬러 / 비밀번호 확인 문구 간격 / 계정아이디 에러메세지 확인, 이미지 용량 초과 시 경고) 및 에…
  css/join.css
  js/join.js
Labels: Update, Fix

#259 [Update] 프로필 수정 페이지 이미지 용량 초과 시 경고 메세지 출력(페이지 이동x)
  js/editprofile.js
  pages/editprofile.html
Labels: Update

#265 [Update] 좋아요, 댓글 UI 겹침 현상 수정
  css/feed.css
  js/home.js
Labels: Update

#271 [Update] 이미지 눌림 현상 해결
  css/postcomment.css
Labels: Update

#272 [Update] 회원가입 / 프로필 수정 페이지 글자수 제한 추가 및 splash 경로 변경
  js/splash.js
  pages/editprofile.html
  pages/join.html
Labels: Update

#278 [Fix] 팔로우,팔로워 limit, css 수정
  css/userList.css
  js/follow.js
Labels: Fix, Design

#276 [Fix] 앨범뷰 버튼 클릭시 같은 게시글만 보이는 현상 수정
  css/feed.css
  js/profile-post.js
Labels: Fix

#274 [Fix] vercel을 이용한 배포 후 기본 이미지가 출력되지 않는 이슈 해결 시도
  js/common.js
  js/editprofile.js
  js/join.js
Labels: Fix

#280 [Add] profile-product 상품 확인모달 채팅버튼 추가
  css/profile.css
  js/profile-product.js
  pages/profile.html
Labels: Add

#282 [Fix] 내 게시글 댓글 페이지와 상대 게시글 댓글 페이지의 모달이 동일하게 동작
  css/modal.css
  css/postcomment.css
  js/postcomment.js
  js/profile-post.js
  pages/postcomment.html
Labels: Update, Fix

#284 [Fix] 좋아요, 댓글 뒤로가기 시 자동반영되지 않는 에러
  css/feed.css
  css/postcomment.css
  css/search-init.css
  js/common.js
  js/feed.js
  js/feedDetail.js
  js/feedmodal.js
  pages/feed.html
  pages/feedDetail.html
  pages/search-init.html
  pages/tab-menu.html
Labels: Update, Fix

#286 [Fix] url 문제로 인한 문제 해결
  js/common.js
  js/editprofile.js
  js/join.js
Labels: Fix

#288 postcomment.css 수정
  css/postcomment.css
Labels: Update

#292 [Add] profile 페이지 채팅버튼 선택 시 이동
  js/profile.js
Labels: Add

#293 [Update] feed.css 폰트 사이즈 수정
  css/feed.css
Labels: Update

#294 [Update] feed.css 폰트 사이즈 수정
  css/feed.css
Labels: Update

#296 [Fix] postcomment.css 수정
  css/postcomment.css
Labels: Update

#298 [Fix] follow 페이지 쿼리스트링, css 수정
  css/userList.css
  js/follow.js
Labels: Fix, Design

#299 [update]home,feed,postcomment css update
  css/feed.css
  css/home.css
  css/postcomment.css
Labels: Update

#301 [Fix] postcomment.css 수정
  css/postcomment.css
Labels: Fix

#303 [Update] 이미지(기본 프로필 이미지, 404, 로고, 홈 피드) 변경 사항 적용 및 새로운 이미지 적용
  assets/images/image-symbol-logo.png
  assets/images/image-symbol-logo.svg
  assets/images/img-404.png
  assets/images/img-404.svg
  assets/images/img-logo.png
  assets/images/img-profile_large.png
  assets/images/img-profile_small.png
  css/404.css
  css/intro.css
  css/splash.css
  js/editprofile.js
  js/home.js
  js/join.js
  pages/404.html
Labels: Add, Update, Delete

#305 [Design] 프로필, 팔로우 html, css 수정
  css/followers.css
  css/followings.css
  css/profile.css
  css/userList.css
  pages/followers.html
  pages/followings.html
Labels: Design

#307 [Rename] 전체 파일 주석 정리
  css/chat.css
  css/chatroom.css
  css/feed.css
  css/imageRegister.css
  css/post.css
  css/postcomment.css
  css/reset.css
  html/imageRegister.html
  js/common.js
  js/editProduct.js
  js/editpost.js
  js/editprofile.js
  js/login.js
  js/post.js
  js/postcomment.js
  js/product.js
  js/profile-post.js
  js/profile-product.js
  js/profile.js
  pages/chat.html
  pages/chatroom.html
  pages/editpost.html
  pages/post.html
  pages/postcomment.html
  pages/profile.html
Labels: Rename

#308 [Rename] 코드 주석 제거
  js/like.js
  js/postcomment.js
  js/profile-post.js
Labels: Rename

#311 [Fix] follow 이미지 엑박 처리, css 수정
  css/userList.css
  js/follow.js
Labels: Fix, Design

#313 [Fix] common.js 이미지 엑박 처리 함수 추가, 홈화면 common.js 클릭 이벤트 에러 예외처리
  css/postcomment.css
  js/common.js
  js/home.js
  js/postcomment.js
  js/search.js
  pages/home.html
Labels: Fix

#315 [Delete] follow 이미지 엑박처리함수 삭제
  js/follow.js
  js/followers.js
  js/followings.js
Labels: Delete

#316 [update]vscode 수정
  .vscode/settings.json
Labels: Update

#320 [Update] profile 페이지들 이미지 에러 처리, common js 이미지 에러처리 옵셔널체이닝 추가
  js/common.js
  js/profile-post.js
  js/profile-product.js
  js/profile.js
Labels: Update

#321 [Update] 검색창 js, html 수정
  js/search.js
  pages/search-result.html
Labels: Update

#322 [Update] splash, login 페이지 토큰 검증 기능 추가
  js/login.js
  js/splash.js
Labels: Add, Update

#324 [Update] input 자동 완성 기능 비활성화 및 모바일 스타일 변경(iOS input 스타일)
  css/editprofile.css
  css/input.css
  css/join.css
  pages/editprofile.html
  pages/join.html
  pages/login.html
Labels: Update, Design

#328 [Update] <html lang=ko> 로 통일
  html/feed.html
  html/modal-chat.html
  html/modal-comment-delete.html
  html/modal-comment-report.html
  html/modal-post.html
  html/modal-product.html
  html/modal-profile.html
  html/tab-menu.html
  pages/home.html
  pages/search-result.html
Labels: Update, Rename

#330 [Fix] 검색창 아이디 넘침 현상 수정
  css/feed.css
  css/postcomment.css
  css/search-result.css
Labels: Fix

#332 [Design] profile 상품 확인 모달 채팅하기버튼 수정
  .vscode/settings.json
  css/profile.css
Labels: Design

#334 [Update] 채팅창 UI 깨짐 현상, 프로필이미지 커서 변경, 프로필페이지 모달 수정
  css/chatroom.css
  css/feed.css
  css/postcomment.css
  css/search-result.css
  js/postcomment.js
  js/profile-post.js
  pages/chatroom.html
Labels: Update

#339 [Fix] common.js url 변경, editProfile 이미지 에러처리
  js/common.js
  js/editprofile.js
Labels: Fix

#341 [Update] postcomment.css 수정
  css/postcomment.css
Labels: Update
